version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
      - ./db/master.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  server:
    image: string_randomizer:latest
    build:
      context: ./string_randomizer/
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    depends_on:
      - db
    environment:
      SERVER_PORT: 8080

networks:
  app: